config/routes.rb
Rails.application.routes.draw do
  root 'people#index' 
 resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end
  def new
    @person = Person.new
  end
    def create
      @person = Person.new(people_params)
      if @person.save
        redirect_to person_path(@person[:id])
      else 
        render :edit
      end
  end
  def detials
    @person = People.find(params[:id])
  end
  def edit
@person= Person.find(params[:id])
  end

  def update 
    @person = Person.find(params[:id])
  
    if @person.update(people_params)
      redirect_to person_path
    else
      render :new
    end
  end
def destroy
  Person.find(params[:id]).destroy
  redirect_to people_path
end


    private 
def people_params
  params.require(:person).permit(:name, :age, :alive, :hair_color, :eye_color, :gender)
end
  end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_homebar.html.erb
<%= link_to "People", people_path %> *
<%= link_to "New", new_person_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/homebar' %>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<% name = Person.find(params[:id]) %>
<h1>Edit <%= name.name %> </h1>
<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
  
  <%= f.label :alive %>
  <%= f.text_field :alive %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1> People </h1>
<% @people.each do |person| %>
 <p> <%= person.name %> </p>
 <p> <%= link_to "Details", person_path(person) %>
 <% end %>

app/views/people/new.html.erb
<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
  
  <%= f.label :alive %>
  <%= f.text_field :alive %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<% person = Person.find(params[:id]) %>
<h1> <%= person.name %> </h1>
<p> <%= link_to "edit", edit_person_path %>
<%= link_to "delete", person, method: :delete %>
<p> 
<p> Age: <%= person.age %> </p>
<p> Gender: <%= person.gender %> </p>
<p> Eye Color: <%= person.eye_color %> </p>
<p> Hair Color: <%= person.hair_color %> </p>
<p> Alive: <%= person.alive %> </p>
</p>